_target_: src.models.lrw_module.LRWLitModule
lr: 0.0003
weight_decay: 0.0001
scheduler_max_epochs: 20

net:
  _target_: src.models.components.lrw_net.LRWVideoModel
  args:
    se: False
    border: False
    n_classes: 500
